version: "3"
services: 
  mongo_db: 
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db
  app: 
    build: . 
    ports: 
      - 8080:8080
    environment:
      APP_NAME: express
      PORT: 8080
      MONGO_URL: mongodb://mongo_db:27017/shop
      JWT_KEY: "hellothisissecretkey"
    depends_on: 
      - mongo_db
volumes:
   mongo_db: {}